alias    l='ls -CF'
alias   la='ls -A'
alias  lsd='ls -d'
alias   ll='ls -l'
alias  lla='ls -lA'
alias  lld='ls -ld'
alias  llh='ls -lh'
alias llhd='ls -lhd'
alias  dir='ls'

alias   l.='ls -d .*'
alias  ll.='ll -d .*'
